/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   demo/lib/common.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html} from 'lit-html';

export {DemoPageBase};

declare class DemoPageBase {
  amf: any;
  latestSelected: any;
  latestType: any;
  query: any;
  constructor();
  _setObservableProperty(prop: any, value: any): void;
  _apiChanged(e: any): void;
  _loadFile(file: any): void;
  _navChanged(e: any): void;
  _searchApiHandler(e: any): void;
  _searchButtonHandler(e: any): void;
  _updateQuery(q: any): void;
  apiListTemplate(): any;
  headerTemplate(): any;
}
